[package]
name = "vmap"
version = "0.1.0"
authors = ["Jeremy Larkin <jeremylarkin@gmail.com>"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
