on: [push]

name: Verify

jobs:
  test_linux: &base
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test_windows:
    <<: *base
    name: Test Windows
    runs-on: windows-latest

  test_macos:
    <<: *base
    name: Test MacOS
    runs-on: macos-latest
